name: user_namager
description: "Prueba tecnica de Double V Partners; es una App de flutter que crea, lee, actualiza usuarios de una base de datos sqlite"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  drift: ^2.15.0
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.0
  path_provider: ^2.1.2
  sqlite3_flutter_libs: ^0.5.20
  path: ^1.9.0
  uuid: ^4.5.1
  intl: ^0.20.2
  collection: ^1.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  drift_dev: ^2.13.0
  flutter_lints: ^5.0.0
  mockito: ^5.4.2
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/addfile.png
    - assets/icon/app_icon.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
